include:
  - 'https://raw.githubusercontent.com/DieterHolvoet/gitlab-ci-deploy/master/deploy.yml'

stages:
  - build
  - deploy
  - post_deploy

composer:
  image: chialab/php-dev:7.3
  stage: build
  script:
    - composer install --no-progress --no-interaction --no-dev
  artifacts:
    paths:
      - public/core
      - public/libraries
      - public/modules/contrib
      - public/profiles/contrib
      - public/themes/contrib
      - drush/Commands
      - vendor/
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - public/core
      - public/libraries
      - public/modules/contrib
      - public/profiles/contrib
      - public/themes/contrib
      - drush/Commands
      - vendor/
  only:
    changes:
      - composer.{lock,json}
  extends:
    - .only_production

theme:
  image: node:8
  stage: build
  script:
    - make
  artifacts:
    paths:
      - public/themes/custom/site_theme/resources/dist
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - public/themes/custom/site_theme/.cache
      - public/themes/custom/site_theme/node_modules
  extends:
    - .only_production

dotenv:
  stage: build
  extends:
    - .create_dotenv
    - .only_production

deploy:
  stage: deploy
  when: manual
  allow_failure: false
  extends:
    - .deploy
    - .only_production

sentry:
  stage: post_deploy
  extends:
    - .create_sentry_release
    - .only_production
